### ISSUE TITLE
ModelAdmin doesn't have Locale

### ISSUE THREAD

**Issue by ArthurConan** [wagtail/wagtail-localize#291]
I can create snippets items for different languages - they have option - Locale (I can choose language in right corner and furthermore I can translate button)

![Screenshot from 2020-12-29 12-05-30](https://user-images.githubusercontent.com/25877951/103276318-de80b680-49ce-11eb-9ac2-390c58ee3d7e.png)

But if I want to create snippet item through **_wagtail.contrib.modeladmin.options.ModelAdmin** - I can't use Locale and translate features (I don't have language chooser in right corner and furthermore I don't have translate button)
![Screenshot from 2020-12-29 12-06-11](https://user-images.githubusercontent.com/25877951/103276324-e2acd400-49ce-11eb-923a-07c4568e2837.png)

I really need list_display, search, filter - so I have to use ModelAdmin
But at the same time - I need the possibilities to create multi-language snippets 

maybe I do something wrong and we can create locale ModelAdmin ???

**Comment by kaedroho** [comment]
There's some features that are currently missing in modeladmin that we would need in order to support it in Localize

 - Hook in new actions so that they can be submitted for translation
 - Replace the edit view for objects being translated
 - Hook in actions in the default editor to allow restarting translation if it was stopped
 - A way to tell if a model has been registered with modeladmin and under what URL the edit view is under

**Comment by ababic** [comment]
Thanks @kaedroho.

> Hook in new actions so that they can be submitted for translation

In modeladmin, the ButtonHelper class is responsible for generating buttons based on a user's permissions, so that would be the place to start here

> Replace the edit view for objects being translated

All of the modeladmin views are swappable, so this should be as simple as defining a custom subclass of `wagtail.contrib.modeladmin.views.EditView` and setting the `edit_view_class` attribute on the modeladmin class.

> Hook in actions in the default editor to allow restarting translation if it was stopped

With control over the view/edit handler/form class/template, I would expect this is possible - but not entirely sure what is being asked here. If it can be done for snippets, I'm sure it can be done for ModelAdmin.

> A way to tell if a model has been registered with modeladmin and under what URL the edit view is under

URLs follow a predictable pattern, so you could try:
`reverse(f"{app_name}_{model_name}_modeladmin_edit", args=[obj.pk])` and fall back to other URL patterns if you hit a `NoReverseMatch`

**Comment by LucasFrezarini** [comment]
Hey @kaedroho, sorry about raising that issue again, but considering what @ababic said, do you guys intend to implement the translation feature in the ModelAdmin in the future? I have a similar use case where we use the ModelAdmin to create some snippets but we also need to make them translatable.

**Comment by enzedonline** [comment]
> Hey @kaedroho, sorry about raising that issue again, but considering what @ababic said, do you guys intend to implement the translation feature in the ModelAdmin in the future? I have a similar use case where we use the ModelAdmin to create some snippets but we also need to make them translatable.

For snippets you just need to use the TranslatableMixin, everything works more or less as translatable pages from there.
![image](https://user-images.githubusercontent.com/72310199/112311059-8ee81900-8ca5-11eb-9061-1a095b7d8e1c.png)

The catch I found, is if the original snippet is deleted, the translated snippets stay orphaned. I'll probably override the form to deal with this when I get a chance.
