### ISSUE TITLE
TypeError: Direct assignment to the reverse side of a related set is prohibited. Use entries.set() instead

### ISSUE THREAD

**Issue by fab10m** [wagtail/wagtail-localize#311]
Hi,

I'm trying to activate multilingual on existing projects with some hundreds of pages, but when I add a locale from Settings>Locales>Add a locale I get the error "Direct assignment to the reverse side of a related set is prohibited. Use entries.set() instead." caused by a GenericRelation
```python
hit_count_generic = GenericRelation(
    HitCount, 'object_pk', related_query_name='entries')
```

It seems that the error get originated inside the module django-modelcluster
```bash
/python3.7/site-packages/modelcluster/models.py", line 170, in __init__
    super(ClusterableModel, self).__init__(*args, **kwargs)
```

Thanks,
Fabio

**Comment by kaedroho** [comment]
Hi @fab10m, thanks for reporting!

Is the `GenericRelation` on a page or a snippet?

**Comment by fab10m** [comment]
On Page.

Fabio

**Comment by fab10m** [comment]
Hi @kaedroho,

I'm still not able to translate page because of this error "TypeError: Direct assignment to the reverse side of a related set is prohibited". Can you please tell if and when you plan to fix the problem?

Regards,
Fabio

**Comment by fordguo** [comment]
use `from modelcluster.fields import ParentalKey` have the same error.

**Comment by fordguo** [comment]
> 
error with `index.Index` mixin

**Comment by maxbellec** [comment]
hello, I am also getting this error when wanting to translate my home page. Full traceback [here](https://0bin.net/paste/KVsgVbTW#fk0EBIIaYaZCfboTzKBsd08ZhD13GecfwC4oj82rW7r).

**Comment by zerolab** [comment]
@maxbellec it would help to have at least a snippet of you homepage model. Are you also using a `GenericRelation`?

**Comment by maxbellec** [comment]
Actually it happened on the home page because one of its child inherited from `wagtail.search.index.Indexed`. The issue also happened when trying to translate snippets that inherited from `TranslatableMixin`, if they also inherited from `TranslatableMixin`.

If you look at the traceback, the issue happened when trying to copy the model. Copying the `index_entries` fails. I was able to fix the issue by overriding the `__init__` method on all classes that inherited from `TranslatableMixin`.

```python
    def __init__(self, *args, **kwargs):
        """Fixes a bug when trying to translate."""
        if "index_entries" in kwargs:
            kwargs.pop("index_entries")
        super().__init__(*args, **kwargs)
```

Maybe `wagtail_localize.models.create_or_update_translation` could be updated to remove `index_entries` before the copy? Happy to help if I can.

**Comment by zerolab** [comment]
@maxbellec ah, this is most helpful
`index_entries` is added via https://github.com/wagtail/wagtail/blob/main/wagtail/search/models.py#L165

As far as I can see all page objects inherit from `index.Indexed` https://github.com/wagtail/wagtail/blob/stable/2.15.x/wagtail/core/models/__init__.py#L183 so this would've surfaced in other cases, no? Unless you mean children like snippets

This feels like a Wagtail core issue, rather than wagtail-localize as `copy_for_translation` (be it for page, or `TranslatableMixin`) is in core.

If this only relates to non-page models, then perhaps we should amend `TranslateabMixin.copy_for_translation` to accept an exclude fields param, as well as take in consideration an `exclude_fields_in_copy` param as in https://docs.wagtail.io/en/stable/reference/pages/model_reference.html#wagtail.core.models.Page.copy_for_translation

**Comment by QuangPhamll** [comment]
Same problem when using `@register_snippet ` with `index.Indexed` and `TranslatableMixin`

**Comment by zerolab** [comment]
Generic relations will now be exluded from copy in the upcoming Wagtail 3.0, 2.16.2, 2.15.5 releases - via https://github.com/wagtail/wagtail/pull/8049

Closing on that basis
