### ISSUE TITLE
Editing snippets in another language breaks 

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail-localize#321]
Steps to reproduce:
  - Go to Snippets > Select a snippet type
  - Hover over one snippet
  - Hit Translate and translate to a particular language
  - Switch to your language with the language selector at the top
  - Try editing your snippet

**Note** This doesn't happen on all snippets, only snippets coming from an inherited model. Example code can be found in Mozilla's Foundation repo here: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/campaigns.py#L55-L70

Error screenshot: 
![image](https://user-images.githubusercontent.com/4743971/107414514-54e4fe00-6acf-11eb-9857-b240e708dc97.png)

Gif reproduction
![snippet-error](https://user-images.githubusercontent.com/4743971/107414522-5adadf00-6acf-11eb-8505-73ca052d827a.gif)

**Comment by kaedroho** [comment]
Thanks for reporting! This one turned out to be a Wagtail core issue, it only changes the `locale` field and doesn't actually copy the snippet which led to the above crash because Wagtail Localize could no longer find the source object.

Fix has been submitted here: https://github.com/wagtail/wagtail/pull/6816

**Comment by kaedroho** [comment]
This is fixed on Wagtail master now: https://github.com/wagtail/wagtail/pull/6816
