### ISSUE TITLE
Deleting translated pages/snippets/etc does not delete their data

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail-localize#402]
It looks like wagtail-localize does not clean up the data associated with translated pages/snippets when deleting, allowing for the following situation:

- create a translation of a page
- localise the content
- publish the localized page
- delete the localized page
- create a new translation of original page for the same locale as before
- all fields are suddenly already translated, using the previous translations

Instead, deleting a localized page should also delete all the associated localized fields, so that a new translation is a proper, new translation.

**Comment by th3hamm0r** [comment]
This issue hit us together with the problem described in #524:
We had a mistyped translation of a subtitle, but it was decided to remove the subtitle completely from the (source) page. Now the source page had no subtitle, but the synced translated page still showed the mistyped string, which was only displayed in the frontend, but not editable in the CMS. The first attempt to fix it, was to remove the translated page and re-create it, but this did not work as described by @Pomax above, since the translations seem to be re-used for the recreated translation...

I think too, that deleting a translation should remove those localized fields, so re-creating a translation should not display previous translations.
