### ISSUE TITLE
Footer and Navbar not Translating

### ISSUE THREAD

**Issue by kuntalk** [wagtail/wagtail-localize#452]
I have integrated wagtail localize with my existing website. Page translation works fine but the static text, footer snippet and navbar does not translate. How to achieve that?

**Comment by enzedonline** [comment]
Hi @kuntalk 

If you add the TranslatableMixin to your snippet model then it can be translated as normal. Make sure to reference _instance_.localized in your code to get the relevant language version.

`from wagtail.core.models import TranslatableMixin`

then declare your model as

```
@register_snippet
class SomeSnippet(TranslatableMixin, models.Model):
    ....
```

For static text, the usual route is PO files, going through the whole {% trans %} or {% blocktrans %}, Django makemessages, edit the PO's searching for the needed strings and weeding out the irrelevant ones, compile the PO's. 

Personally, I find this whole process laborious and unnecessary since it requires an admin with console access.

I've made a snippet and template tag to deal with this and take advantage of Wagtail-localize, passes the onus for translating on to the editors instead.

There are caveats in this - it requires the necessary placeholder in the template, and requires that the editor knows what the placeholders are and doesn't try to change those (well, nothing breaks, placeholders without text are blank, snippet instances without matching placeholder don't show). The templates should be well documented for this (as they should be in any case). You can restrict snippet access to certain user groups so that only the senior editor has access to this for example.

Code for the snippet:

```
@register_snippet
class TemplateText(TranslatableMixin, ClusterableModel):
    template_set = models.CharField(
        unique=True,
        max_length=50,
        verbose_name="Set Name",
        help_text=_("The set needs to be loaded in template tags then text references as {{set.tag}}")
    )    

    translatable_fields = []
    
    panels = [
        FieldPanel("template_set"),
        MultiFieldPanel(
            [
                InlinePanel("templatetext_items"),
            ],
            heading=_("Text Items"),
        ),
    ]

    def __str__(self):
        return self.template_set
    
    class Meta:
        verbose_name = _('Template Text')
        unique_together = ('translation_key', 'locale')

class TemplateTextSetItem(TranslatableMixin, Orderable):
    set = ParentalKey(
        "TemplateText",
        related_name="templatetext_items",
        help_text=_("Template Set to which this item belongs."),
        verbose_name="Set Name",
    )
    template_tag = models.SlugField(
        max_length=50,
        help_text=_("Enter a tag without spaces, consisting of letters, numbers, underscores or hyphens."),
        verbose_name="Template Tag",
    )    
    text = models.TextField(
        null=True,
        blank=True,
        help_text=_("The text to be inserted in the template.")
    )

    translatable_fields = [
        TranslatableField('text'),
    ]

    panels = [
        RegexPanel('template_tag', '^[-\w]+$'),
        FieldPanel('text'),
    ]

    def __str__(self):
        return self.template_tag

    class Meta:
        unique_together = ('set', 'template_tag'), ('translation_key', 'locale')
```

The RegexPanel is something I wrote to stop people typing invalid characters since it's for a slugfield (I need to work out a way to stop invalid pasted characters some time). It's not necessary, I just don't like forms that let you type in invalid characters and then tell you about it after you press save. 

The translatable_fields declaration in template_text model ensures the set name isn't translated (has to be the same for all languages), and in the set item, ensures only the text and not the placeholder (template_tag) is translated, you need the placeholder to remain the same regardless of language.

Code for the RegexPanel below, or you can just use a normal FieldPanel for that and let the form validation throw the error. 

```
from wagtail.admin.edit_handlers import (
    FieldPanel,
)

class RegexPanel(FieldPanel):
    def __init__(self, field_name, pattern, *args, **kwargs):
        self.pattern = pattern
        super().__init__(field_name, *args, **kwargs)

    def clone_kwargs(self):
        kwargs = super().clone_kwargs()
        kwargs.update(
            field_name=self.field_name,
            pattern=self.pattern,
        )
        return kwargs

    field_template = "edit_handlers/regex_panel_field.html"

    def on_form_bound(self):
        self.form.fields[self.field_name].__setattr__('pattern',self.pattern)
        super().on_form_bound()
```

And the regex panel template:

```
{% load core_tags wagtailadmin_tags %}
{% get_template_set 'common' as trans %}

<div class="field {{ field|fieldtype }} {{ field|widgettype }} {{ field_classes }}" {% if include_contentpath|default_if_none:True %}data-contentpath="{{ field.name }}"{% endif %}>
    {% if show_label|default_if_none:True %}{{ field.label_tag }}{% endif %}
    <div class="field-content">
        <div class="input {{ input_classes }} ">
            {% block form_field %}
                {% regex_render_with_errors field as htmlcode %}
                {{ htmlcode }}                
            {% endblock %}

            {# This span only used on rare occasions by certain types of input #}
            <span></span>
        </div>
        {% if show_help_text|default_if_none:True and field.help_text %}
            <p class="help">{{ field.help_text }}</p>
        {% endif %}

        {% if field|has_unrendered_errors %}
            <p class="error-message">
                {% for error in field.errors %}
                    <span>{{ error|escape }}</span>
                {% endfor %}
            </p>
        {% endif %}
    </div>

    {% if show_add_comment_button %}
        <div class="field-comment-control">
            <button type="button" data-component="add-comment-button" data-comment-add class="u-hidden" aria-label="{{ trans.add_comment }}">
                <svg class="icon icon-comment-add initial icon-default" aria-hidden="true" focusable="false"><use href="#icon-comment-add"></use></svg>
                <svg class="icon icon-comment-add initial icon-reversed" aria-hidden="true" focusable="false"><use href="#icon-comment-add-reversed"></use></svg>
            </button>
        </div>
    {% endif %}
</div>
```

core_tags is where I have the template text tag code, also the regex_render_with_errors which adds the necessary javascript:

```
@register.simple_tag()
def regex_render_with_errors(bound_field):
    id = bound_field.auto_id
    rendered_field = render_with_errors(bound_field)
    if f'id="{id}"' in rendered_field:
        fn = id.replace('-','_')
        script = f' onkeydown="return keydownhandler_{fn}(event)">\
        <script>function keydownhandler_{fn}(event) \
            {{if (!(/{bound_field.field.pattern}/.test(event.key))){{\
                return false;}} }} \
        </script>'       
        return mark_safe(rendered_field.replace('>', script))
    return rendered_field

```
If you're skipping the RegexPanel, from here on is relevant again:

The admin page for the snippets looks like the following now:

![image](https://user-images.githubusercontent.com/72310199/133103567-7e9c5436-0c54-4ede-9a98-20dd66944c8e.png)

finally, in your templates with static text, reference your template tag file (in my case, core_tags) and load the text set for that template (or you could load multiple and assign to different variables). 

`{% get_template_set 'common' as trans %}` <- change 'trans' to whatever works for you

Code for get_template_set:

```
@register.simple_tag()
def get_template_set(set):
    try:
        template_set = TemplateText.objects.filter(template_set=set).first().localized 
        if template_set:
            items = template_set.templatetext_items.all()
            if items:
                text_dict = {}
                for i in items:
                    text_dict[i.template_tag] = i.text
                return text_dict
        return TemplateText.objects.none()
                
    except (AttributeError, TemplateText.DoesNotExist):
        return TemplateText.objects.none()    
```

It loads the template set and returns it as a dictionary with the placeholder names as key and the translated text as the matching value. ie with trans as the variable name, trans._placeholder_ will give you the translated static text 

Use it in place of static text (404 template as an example):

```
    {% get_template_set 'page-error' as trans %}
    <title>{{ trans.404_title }}</title>
    <div class="container-fluid text-center" style="position: absolute; top: 50%;-ms-transform: translateY(-50%); transform: translateY(-50%);" >
        <div class="px-3">
            <p><i class="fas fa-exclamation-triangle fa-3x text-warning"></i></p>
            <h1>{{ trans.404_heading }}</h1>
            {% trans_page_from_slug 'contact' True as contact %}
            <h5>{{ trans.404_message }} <a href='{{ contact.url }}'>{{ trans.contact }}</a>.</h5>
        </div>
    </div>
```

Well, hopefully that's useful to you (or someone) ;)

**Comment by enzedonline** [comment]
I should probably also mention that if you have a snippet looking up values from another snippet, it'll return everything as choices (ie all the translated values for the look up snippet, not just for the ones relevant to the language of the snippet you're editing).

eg, a colour picker to choose between red and blue with english and spanish will show red, rojo, blue, azul in the dropdown.

I wrote some code to filter the other language choices out, it was surprisingly long and convoluted and ultimately hinges on the url of the snippet edit page since there is no other way to get the language of the snippet being edited (editor can set the admin interface to english and be editing a spanish page for example). Anyway, if you're interested in that, I can put that up as well, or have a look through the models and edit_handlers at https://github.com/enzedonline/enzedonline/tree/master/menu

There should be a more robust way of doing this.

**Comment by zerolab** [comment]
Closing this as this was not a localize issue per se. Thank you Rich for the help and examples here
