### ISSUE TITLE
How to edit promote panel for translation?

### ISSUE THREAD

**Issue by maxbellec** [wagtail/wagtail-localize#498]
Hi,
Many thanks for the great software.
I read the docs, but I fail to find how I can edit the promote panel for a translated page.
More specifically, I want the promote panel to include `seo_title` and `search_description`. I can edit these fields for the original language, but on the page for the translated language, I can only edit the slug. If I stop the sync translation, I have all the options and I can edit it.
I tried to edit `translatable_fields` or `override_translatable_fields`, but it did not seem to have any effect :thinking:.

**Comment by Redjam** [comment]
Hi @maxbellec, 

I don't think this is an issue.

I assume your are using Wagtailmetadata. 

If you have created a page and its translations before adding MetadataPageMixin, you need to sync the page in order to make the new fields available in the tanslated versions. That way, seo_title and search_description appear in promote panel.

**My setup:**
wagtail-metadata==3.5.0
wagtail-localize==1.0.1
wagtail==2.15.4

![Capture d’écran 2022-03-11 à 17 05](https://user-images.githubusercontent.com/6397887/157904939-21805cde-312b-4bb4-b2e3-c8ce6aa6463c.jpg)

**Comment by ishaboth** [comment]
Hi @Redjam,

i'm having the same Problem as @maxbellec, and i'm not using wagtail-metadata.

The "Title tag" and "Meta description" are part of my base wagtail installation. 

I have some fields in my abstract "Page" model, that i use as base for my other pages, which are added to "promote_panels" instead of "content_panels". 
When translating in the UI, i'm only offered the fields in "content_panels", but not those within "promote_panels". 

My setup:
wagtail==2.16.1
wagtail-localize==1.1

**Comment by calind** [comment]
I've added the follwing to my page models:
```python
class HomePage(Page):
...
    override_translatable_fields = [
        SynchronizedField("seo_title"),
        SynchronizedField("search_description"),
    ]
```

**Comment by zerolab** [comment]
Closing as this should just work. Please re-open if that is still not the case, and do share more steps/code snippets to reproduce
