### ISSUE TITLE
V1.2 - snippets language drop-down is blank until hover

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail-localize#576]
![image](https://user-images.githubusercontent.com/72310199/169782488-d8f26b9e-1762-47e3-b3a6-d9ed535e1a53.png)

When I hover with mouse, it's visible as expected:

![image](https://user-images.githubusercontent.com/72310199/169782689-4197b3cc-4e63-4e24-8289-2e8160222728.png)

The problem seems to be the `u-btn-current` css class that sets color to #fff but no background-color is set

Adding the button class to the element fixes the issue:

`<a href="javascript:void(0)" aria-label="English" class="button c-dropdown__button u-btn-current w-no-underline">
`

**Comment by enzedonline** [comment]
@zerolab huh, I'd never seen that was an option before now, which version brought that in? 
Just adding "wagtail_localize.modeladmin" to my app list fixes it.
Thanks :)

**Comment by zerolab** [comment]
I should have been clearer. The screenshots are the regular Wagtail snippets UI, right? in that case it is an issue for Wagtail core. Before opening an issue there, do you get the same with just the core simple_translation app (i.e. using `wagtail.contrib.simple_translation` instead of `"wagtail_localize"` in installed apps. Sorry, currently not able to confirm this myself

**Comment by enzedonline** [comment]
@zerolab  I'd need to create a whole new test site to look at that ... I've never used it.

I see this issue on the snippet page, but if I drill into an instance of the snippet, the drop-down displays fine:

![image](https://user-images.githubusercontent.com/72310199/169843360-52bff227-a7ad-4f07-91ca-cb232d90581c.png)
