### ISSUE TITLE
Pages that don't have the supported language.

### ISSUE THREAD

**Issue by bingimar** [wagtail/wagtail-localize#678]
I have a site in around 20 languages. I'm using wagtail localize to handle translation of articles.

When a user has selected Turkish and clicks the articles link the site defaults to English BUT the navbar flag changes to English as well.

What I would like to do is if article is not available in the selected language, it defaults to english but the flag in the nav is still in the selected language in this case the Turkish flag.

Help greatly appreciated.

**Comment by zerolab** [comment]
Hey @bingimar,

wagtail-localize does not provide any flag functionality, so that is a custom implementation.
I suggest joining the Wagtail Slack (see instructions https://github.com/wagtail/wagtail/wiki/Slack) and asking in `#support` or `#multi-language`, providing additional details such a code snippet for your navbar which shows the language and flag, as well as some example URLs


The wagtail-localize docs do have an example for a language switcher (https://www.wagtail-localize.org/tutorial/4-templates/#adding-a-language-switcher), but even that doesn't do anything with the language.

**Comment by zerolab** [comment]
@enzedonline a PR changing that will be more than welcome ;)

**Comment by enzedonline** [comment]
@zerolab it's probably a bit long for that page ... requires a template tag to determine the best translation page and handle routable pages properly (get_translation will drop the kwargs), and a routed view for django pages plus activating the language and setting the language cookie ... then there's the flag sprite sheet and the menu template ... 

I'll write a blog for it one of these days ...

![switcher](https://user-images.githubusercontent.com/72310199/224744870-12cbc3d3-2176-43a6-9f07-43138f08c8ed.png)
